//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StefaniniPruebaTecnica.DataStorage.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBancaria()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BancoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> TipoCuentaId { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual TipoCuentaBancaria TipoCuentaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
