//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StefaniniPruebaTecnica.DataStorage.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StefaniniDBEntities : DbContext
    {
        public StefaniniDBEntities()
            : base("name=StefaniniDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<TipoCuentaBancaria> TipoCuentaBancaria { get; set; }
        public virtual DbSet<TipoTransaccion> TipoTransaccion { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
    
        public virtual ObjectResult<Transacciones> ObtenerTransacciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transacciones>("ObtenerTransacciones");
        }
    }
}
